spring:
    datasource:
        url: ${CONVERSATION_MANAGER_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/knowledge_manager}
        username: ${CONVERSATION_MANAGER_DATASOURCE_USERNAME:horizony}
        password: ${CONVERSATION_MANAGER_DATASOURCE_PASSWORD:hzy0304.}
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-init-sql: SET TIME ZONE 'UTC'

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com

    buckets:
      document: knowledge-manager-documents


document:
  upload:
    max-count: 10
    url-expiration-seconds: 3600
